a = input('Digite algo ')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaço?', a.isspace())
print('É um número',a.isnumeric())
print('é alfabético:',a.isalpha())
print('É um alfanúmerico?', a.isalnum())
print('Esta em maiusculo?',a.isupper())
print('Está em minuscúlo?',a.islower())
print('Está Capitalizada',a.istitle())